export type Cat = "all" | "wedding" | "adat" | "animasi" | "non-wedding";
export type CatalogItem = { slug: string; cat: Cat; title: string; badge?: string; demoSlugs?: string[] };
export const CATALOG: CatalogItem[] = [
  { slug: "noir-eternel", cat: "wedding", title: "Noir Éternel" },
  { slug: "ivory-garden", cat: "wedding", title: "Ivory Garden" },
  { slug: "celestial-vow", cat: "wedding", title: "Celestial Vow" },
  { slug: "lumiere", cat: "wedding", title: "Lumière" },
  { slug: "heritage-silk", cat: "wedding", title: "Heritage Silk" },
  { slug: "serene-arch", cat: "wedding", title: "Serene Arch" },
  { slug: "blush-bloom", cat: "wedding", title: "Blush Bloom" },
  { slug: "modern-minimal", cat: "wedding", title: "Modern Minimal" },
  { slug: "classic-ivory", cat: "wedding", title: "Classic Ivory" },
  { slug: "midnight-rose", cat: "wedding", title: "Midnight Rose" },
  { slug: "sage-ritual", cat: "wedding", title: "Sage Ritual" },
  { slug: "velvet-noon", cat: "wedding", title: "Velvet Noon" },
  { slug: "adagio", cat: "wedding", title: "Adagio" },
  { slug: "solenne", cat: "wedding", title: "Solenne" },
  { slug: "amandine", cat: "wedding", title: "Amandine" },
  { slug: "engagement-eternel", cat: "wedding", title: "Engagement Éternel" },
  { slug: "eclat-noir", cat: "wedding", title: "Éclat Noir" },
  { slug: "vermeil", cat: "wedding", title: "Vermeil" },
  { slug: "moire-sable", cat: "wedding", title: "Moiré Sable" },
  { slug: "orangerie", cat: "wedding", title: "Orangerie" },
  { slug: "opaline", cat: "wedding", title: "Opaline" },
  { slug: "velours-nuit", cat: "wedding", title: "Velours Nuit" },
  { slug: "atelier-blush", cat: "wedding", title: "Atelier Blush" },
  { slug: "maison-lace", cat: "wedding", title: "Maison Lace" },
  { slug: "jardin-noir", cat: "wedding", title: "Jardin Noir" },
  { slug: "aureline", cat: "wedding", title: "Aurèline" },
  { slug: "brume", cat: "wedding", title: "Brume" },
  { slug: "chantelle", cat: "wedding", title: "Chantelle" },
  { slug: "seraphine", cat: "wedding", title: "Séraphine" },
  { slug: "divine-ivory", cat: "wedding", title: "Divine Ivory" },
  { slug: "adat-jawa-ageng", cat: "adat", title: "Jawa Ageng" },
  { slug: "adat-sunda-kencana", cat: "adat", title: "Sunda Kencana" },
  { slug: "adat-minang-balairung", cat: "adat", title: "Minang Balairung" },
  { slug: "adat-batak-gorga", cat: "adat", title: "Batak Gorga" },
  { slug: "adat-bali-prasada", cat: "adat", title: "Bali Prasada" },
  { slug: "adat-melayu-seri", cat: "adat", title: "Melayu Seri" },
  { slug: "adat-betawi-sophi", cat: "adat", title: "Betawi Sophi" },
  { slug: "adat-jawa-prameswari", cat: "adat", title: "Jawa Prameswari" },
  { slug: "pembayun-elegant", cat: "adat", title: "Pembayun Elegant" },
  { slug: "sangkala", cat: "adat", title: "Sangkala" },
  { slug: "animasi-lune", cat: "animasi", title: "Animasi Lune" },
  { slug: "animasi-aurelia", cat: "animasi", title: "Animasi Aurelia" },
  { slug: "animasi-etincelle", cat: "animasi", title: "Animasi Étincelle" },
  { slug: "animasi-velour", cat: "animasi", title: "Animasi Velour" },
  { slug: "animasi-rivage", cat: "animasi", title: "Animasi Rivage" },
  { slug: "animasi-nocturne", cat: "animasi", title: "Animasi Nocturne" },
  { slug: "animasi-celestine", cat: "animasi", title: "Animasi Célestine" },
  { slug: "khitan-arslan-elegant", cat: "non-wedding", title: "Khitan Arslan" },
  { slug: "khitan-safir", cat: "non-wedding", title: "Khitan Safir" },
  { slug: "khitan-amir", cat: "non-wedding", title: "Khitan Amir" },
  { slug: "aqiqah-noura", cat: "non-wedding", title: "Aqiqah Noura" },
  { slug: "aqiqah-izzah", cat: "non-wedding", title: "Aqiqah Izzah" },
  { slug: "aqiqah-zayyan", cat: "non-wedding", title: "Aqiqah Zayyan" },
  { slug: "birthday-liora", cat: "non-wedding", title: "Birthday Liora" },
  { slug: "birthday-elio", cat: "non-wedding", title: "Birthday Elio" },
  { slug: "tasmiyah-elegant", cat: "non-wedding", title: "Tasmiyah Elegant" },
  { slug: "tedak-siten-prameswari", cat: "non-wedding", title: "Tedak Siten" },
  { slug: "walimatul-khitan-elite", cat: "non-wedding", title: "Walimatul Khitan Elite" },
  { slug: "aqiqah-hana-prameswari", cat: "non-wedding", title: "Aqiqah Hana" },
  { slug: "ultah-aria", cat: "non-wedding", title: "Ultah Aria" },
];
export function thumbFor(slug: string) {
  return `https://picsum.photos/seed/mstory-${slug}/420/760`;
}
